name: Deploy to the EKS

on:
  workflow_dispatch:
    inputs:
      trigger_next:
        description: 'Whether to run the subsequent workflows after triggering this one manully.'
        required: false
        default: false
  repository_dispatch:
    types: [trigger-workflow-2]
  

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}           # set this to your Amazon ECR repository name
 
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2
      with:
          ref: ${{ github.event.client_payload.sha }}
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Kube config update
      run: |
       aws eks update-kubeconfig --name web_deployment-cluster
    - name: Deploy the image
      working-directory: eks
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}      
      run: |
       #docker pull $ECR_REGISTRY/$ECR_REPOSITORY:latest
       sleep 15s
       kubectl apply -f deployment.yaml
       kubectl apply -f service.yaml
    
