name: Deploy to the EKS

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}           # set this to your Amazon ECR repository name
 
permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to EKS
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Kube config update
      run: |
       aws eks update-kubeconfig --name web_deployment-cluster
    - name: Deploy the image
      run: |
       pwd
       kubectl apply -f /eks/deployment.yaml
       kubectl apply -f /eks/service.yaml

    
